---
title: "Influence of systolic blood pressure on coronary heart disease"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Influence of systolic blood pressure on coronary heart disease}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

|Error types | Likelihood | Response | Covariate with error | Other covariate(s) |
|:-----------|:----------|:--------|:----------|:------------|
|Classical | Binomial | `disease` | `sbp1`, `sbp2` | `smoking` |


```{r setup}
library(inlami)
```


```{r}
prior.beta <- c(0, 0.01)
prior.alpha0 <- c(0, 1)
prior.alphaz <- c(0, 1)

framingham_model <- fit_inlami(formula_moi = disease ~ sbp + smoking,
                               formula_imp = sbp ~ smoking,
                               family_moi = "binomial", 
                               data = framingham,
                               error_type = "classical", 
                               repeated_observations = TRUE,
                               prior.prec.classical = c(100, 1),
                               prior.prec.imp = c(10, 1),
                               initial.prec.classical = 100,
                               initial.prec.imp = 10)
```

```{r, echo = FALSE, results='asis'}
framingham_stacks <- show_data_structure(framingham_model$stack_data)
cat("$$\n")
cat(framingham_stacks$matrix_string)
cat("\n$$")
```


```{r}
summary(framingham_model)
```

```{r}
plot(framingham_model)
```




