---
title: "Survival data with repeated systolic blood pressure measurements"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{nhanes_survival}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(inlami)
library(INLA)
```


```{r}
surv_list <- as.list(nhanes_survival)
surv_list$surv <- INLA::inla.surv(time = nhanes_survival$t/10, event = nhanes_survival$d)

survival_stacks <- make_inlami_stacks(formula_moi = surv ~ sbp + age + smoking + sex + diabetes,
  formula_imp = sbp ~ age + smoking + sex + diabetes,
  data = surv_list,
  error_type = c("classical", "missing"),
  repeated_observations = TRUE)

survival_model <- fit_inlami(
  formula_moi = surv ~ sbp + age + smoking + sex + diabetes,
  formula_imp = sbp ~ age + smoking + sex + diabetes,
  family_moi = "weibull.surv",
  data = surv_list,
  error_type = c("classical", "missing"),
  repeated_observations = TRUE,
  control.family = list(
    list(hyper = list(alpha = list(param = prior.exp,
                                   initial = log(exp.init),
                                   fixed = FALSE))),
    list(hyper = list(prec = list(initial = log(prec.u),
                                  param = prior.prec.u,
                                  fixed = FALSE))),
    list(hyper = list(prec = list(initial = log(prec.x),
                                  param = prior.prec.x,
                                  fixed = FALSE)))),
  control.predictor=list(link=3))
```

## Manual stacking 

```{r}
n <- nrow(nhanes_survival)

# Regression model of interest
# y = beta.0 + beta.x*x_true + beta.z*z + e
stk_moi <- inla.stack(data = list(Y = cbind(nhanes_survival$t, nhanes_survival$d, NA, NA, NA)),
                      A = list(1),
                      effects = list(
                        list(beta.0 = rep(1, n),
                             beta.sbp1 = 1:n,
                             beta.diabetes = nhanes_survival$diabetes)),
                      tag = "moi")

Y.surv <- inla.surv(nhanes_survival$t/10, nhanes_survival$d)

stk_moi <- inla.stack(data = list(Y = list(Y.surv, rep(NA, n), rep(NA, n))),
                      A = list(1),
                      effects = list(
                        list(beta.0 = rep(1, n),
                             beta.sbp1 = 1:n,
                             beta.diabetes = nhanes_survival$diabetes)),
                      tag = "moi")

# Classical measurement error model
# x = r + u_c
stk_c <- inla.stack(data = list(Y = cbind(NA, NA, nhanes_survival$sbp1, NA)),
                    A = list(1),
                    effects = list(
                      list(id.sbp1 = 1:n,
                           weight.sbp1 = 1)),
                    tag = "classical")

# Imputation/exposure model
# 0 = r + alpha.0 + alpha.z + e_r
stk_imp <- inla.stack(data = list(Y = cbind(NA, NA, NA, rep(0, n))),
                      A = list(1),
                      effects = list(
                        list(id.sbp1 = 1:n,
                             weight.sbp1 = rep(-1, n),
                             alpha.0 = rep(1, n),
                             alpha.diabetes = nhanes_survival$diabetes)),
                      tag = "imputation")

# Stack them on top of each other
stk_full <- inla.stack(stk_moi, stk_c, stk_imp)

formula <- Y ~ - 1 + beta.0 + beta.diabetes +
  f(beta.sbp1, copy = "id.sbp1",
    hyper = list(beta = list(param = c(0, 0.01), fixed = FALSE))) +
  f(id.sbp1, weight.sbp1, model = "iid", values = 1:n,
    hyper = list(prec = list(initial = -15, fixed = TRUE))) +
  alpha.0 + alpha.diabetes

model_sim <- inla(formula, data = inla.stack.data(stk_full),
                  family = c("gaussian", "gaussian", "gaussian", "gaussian"),
                  control.family = list(
                    list(hyper = list(prec = list(initial = log(initial.prec.y),
                                                  param = prior.prec.y,
                                                  fixed = FALSE))),
                    list(hyper = list(prec = list(initial = log(initial.prec.u_b),
                                                  param = prior.prec.u_b,
                                                  fixed = FALSE))),
                    list(hyper = list(prec = list(initial = log(initial.prec.u_c),
                                                  param = prior.prec.u_c,
                                                  fixed = FALSE))),
                    list(hyper = list(prec = list(initial = log(initial.prec.r),
                                                  param = prior.prec.r,
                                                  fixed = FALSE)))
                  ),
                  control.predictor = list(compute = TRUE)
)

summary(model_sim)
```

